#!/bin/bash

echo "🔧 PROBLÈME TEMPLATE ID EMAILJS - SOLUTION RAPIDE"
echo ""

echo "❌ TEMPLATE ID INVALIDE DÉTECTÉ"
echo "   Template actuel: template_wvesgq6 → 'not found'"
echo ""

echo "🎯 COMMENT TROUVER LES VRAIS TEMPLATE IDS :"
echo ""
echo "1. Allez sur: https://dashboard.emailjs.com/admin"
echo "2. Cliquez sur 'Email Templates'"
echo "3. Vous verrez vos templates avec leurs IDs"
echo ""

echo "📝 TEMPLATES REQUIS (3 au total) :"
echo ""
echo "Template 1 - BAT Client:"
echo "   Nom: 'BAT à valider'"  
echo "   ID: template_xxxxxx (à noter)"
echo "   Sujet: BAT à valider - {{file_name}}"
echo ""
echo "Template 2 - Notification Validation:"
echo "   Nom: 'BAT validé'"
echo "   ID: template_yyyyyy (à noter)"  
echo "   Sujet: ✅ BAT Validé - {{file_name}}"
echo ""
echo "Template 3 - Notification Rejet:"
echo "   Nom: 'BAT rejeté'"
echo "   ID: template_zzzzzz (à noter)"
echo "   Sujet: ❌ BAT Rejeté - {{file_name}}"
echo ""

echo "🚀 SOLUTION RAPIDE SI PAS DE TEMPLATES :"
echo ""
echo "Si vous n'avez aucun template, créez-en un rapidement:"
echo "1. Dashboard → Email Templates → Create New Template"
echo "2. Nom: 'BAT Test'"
echo "3. Sujet: Test - {{file_name}}"
echo "4. Contenu: Bonjour, voici votre BAT: {{bat_url}}"
echo "5. Sauvez et notez l'ID généré"
echo ""

echo "🧪 TESTER LE NOUVEAU TEMPLATE :"
echo "   Utilisez: https://bat-orcin.vercel.app/test-service-id"
echo "   Entrez le nouveau Template ID et testez"
echo ""

echo "⚡ MISE À JOUR RAPIDE UNE FOIS VALIDÉ :"
echo ""
echo "# Localement (.env.local):"
echo "NEXT_PUBLIC_EMAILJS_TEMPLATE_BAT=template_NOUVEAU_ID"
echo ""
echo "# Sur Vercel:"
echo "npx vercel env rm NEXT_PUBLIC_EMAILJS_TEMPLATE_BAT production"
echo "npx vercel env add NEXT_PUBLIC_EMAILJS_TEMPLATE_BAT production"
echo "npx vercel --prod"

echo ""
echo "💡 ASTUCE: Commencez par créer UN SEUL template de test"
echo "   pour valider que ça marche, puis créez les autres après."
