#!/bin/bash

echo "🚨 SOLUTION URGENTE - Service ID EmailJS ne fonctionne plus"
echo ""

echo "Le Service ID 'service_xb0o03d' retourne 'not found'"
echo "Cela peut arriver si:"
echo "- Le service a été suspendu (quota dépassé)"
echo "- Le service a été supprimé"
echo "- Problème temporaire EmailJS"
echo ""

echo "🎯 SOLUTION RAPIDE:"
echo ""
echo "1. CRÉER UN NOUVEAU SERVICE:"
echo "   - Allez sur https://dashboard.emailjs.com/admin"
echo "   - Cliquez 'Email Services' → 'Add New Service'"
echo "   - Choisissez votre provider (Gmail recommandé)"
echo "   - Suivez l'assistant de configuration"
echo "   - NOTEZ le nouveau Service ID (ex: service_abc123)"
echo ""

echo "2. TESTER LE NOUVEAU SERVICE:"
echo "   - Utilisez la page: https://bat-orcin.vercel.app/test-service-id"
echo "   - Entrez le nouveau Service ID"
echo "   - Testez l'envoi"
echo ""

echo "3. METTRE À JOUR LA CONFIGURATION:"
echo "   Une fois validé, mettez à jour:"

echo ""
echo "# Localement (.env.local):"
echo "NEXT_PUBLIC_EMAILJS_SERVICE_ID=nouveau_service_id"
echo ""

echo "# Sur Vercel:"
echo "npx vercel env rm NEXT_PUBLIC_EMAILJS_SERVICE_ID production"
echo "npx vercel env add NEXT_PUBLIC_EMAILJS_SERVICE_ID production"
echo "# Puis entrez le nouveau Service ID"
echo ""

echo "4. REDÉPLOYER:"
echo "npx vercel --prod"
echo ""

echo "⚡ ALTERNATIVE TEMPORAIRE:"
echo "Si vous n'avez pas le temps de créer un nouveau service,"
echo "utilisez temporairement un service SMTP en attendant:"
echo ""
echo "Dans .env.local, configurez:"
echo "EMAIL_HOST=smtp.gmail.com"
echo "EMAIL_PORT=587"
echo "EMAIL_USER=votre_email@gmail.com"
echo "EMAIL_PASS=votre_mot_de_passe_app"
echo ""
echo "Le système détectera automatiquement SMTP et l'utilisera"
echo "comme fallback si EmailJS ne fonctionne pas."

echo ""
echo "📞 Besoin d'aide ? Le système BAT peut fonctionner avec:"
echo "   - EmailJS (priorité 1)"
echo "   - SMTP Gmail/Outlook (fallback)"
echo "   - Tout autre service SMTP"
